apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
        - name: ibm-cr-secret

      containers:
        - name: order-service
          image: icr.io/ecommerceapp-v1/order-service:latest
          ports:
            - containerPort: 5000
