apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  type: NodePort    
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002
