apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  type: NodePort   
  ports:
    - protocol: TCP
      port: 5000    
      targetPort: 5000
      nodePort: 30001  
